export const SUPPORTED_LANGUAGES = {
  en: 'English',
  es: 'Español'
}


export const enum ACTION_TYPES  {
  INTERCHANGE_LANGUAGES = 'INTERCHANGE_LANGUAGES',
  SET_FROM_LANGUAGE = 'SET_FROM_LANGUAGE',
  SET_TO_LANGUAGE = 'SET_TO_LANGUAGE',
  SET_FROM_TEXT = 'SET_FROM_TEXT',
  SET_RESULT_TEXT = 'SET_RESULT_TEXT',
}

export const AUTO_LANGUAGE = 'auto';

